# Generated by Django 3.1.4 on 2020-12-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('dep_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
