# Generated by Django 3.1.4 on 2020-12-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201205_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_full_name',
            new_name='full_name',
        ),
    ]
